#include <iostream>
#include <vector>
using namespace std;

// Function to calculate d(n)
int d(int n) {
    int sum = n;
    while (n > 0) {
        sum += n % 10;  // Add the last digit
        n /= 10;        // Remove the last digit
    }
    return sum;
}

int main() {
    const int LIMIT = 1000000;
    vector<bool> isGenerated(LIMIT + 1, false); // Initialize all as false

    // Mark all numbers that can be generated by d(n)
    for (int i = 1; i <= LIMIT; ++i) {
        int generated = d(i);
        if (generated <= LIMIT) {
            isGenerated[generated] = true;
        }
    }

    // Print all self-numbers
    for (int i = 1; i <= LIMIT; ++i) {
        if (!isGenerated[i]) {
            cout << i << endl;
        }
    }

    return 0;
}
